project_id = "dsljcorhhnushvbvsrmh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.handle-transaction-status]
verify_jwt = false

[functions.vtpass-bill-payment]
verify_jwt = true
